#!/bin/bash

echo ""
echo "Panda V0.4 installer"

make clean
make
rm -f -r *.o

rm -f -r bin
mkdir bin

mv ./panda_main bin/
cp ./sample.txt bin/

echo ""
echo "panda_main is now installed under bin/"
echo ""

exit 0
